version: '3'
services:
  jmt:
    container_name: jmt
    image: jungesmuensterschwarzach/timer:latest
    restart: always
    networks:
      jenkins:
        ipv4_address: 172.16.1.230
networks:
  default:
    external:
      name: jenkins
  jenkins:
    external: true